# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: "pt-BR"

early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    base_branches: ["main", "dev"]
    drafts: false
chat:
  auto_reply: true
# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "pt-BR"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    base_branches: ["main", "dev"]
    drafts: false
chat:
  auto_reply: true
