import "@repo/ui/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthProvider, QueryProvider } from "@repo/hook-services";
import { Toaster } from "@repo/ui/components/ui/sonner";
import { TooltipProvider } from "@repo/ui/components/ui/tooltip";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Docs",
	description: "Generated by create turbo",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}): JSX.Element {
	const cookieStore = cookies();
	const token = cookieStore.get("USER_TOKEN");

	const clientToken = token?.value
		? {
				clientId: "1",
				token: token.value,
			}
		: null;

	return (
		<html lang="en">
			<head>
				<link rel="icon" type="image/x-icon" href="/favicon.ico" />
			</head>
			<QueryProvider>
				<AuthProvider auth={clientToken}>
					<TooltipProvider>
						<body className={inter.className}>
							{children}
							<Toaster />
						</body>
					</TooltipProvider>
				</AuthProvider>
			</QueryProvider>
		</html>
	);
}
