#!/usr/bin/env sh
# . "$(dirname -- "$0")/_/husky.sh"

# yarn format && git add -A .

# .husky/pre-commit
prettier $(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g') --write --ignore-unknown
git update-index --again
