#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# yarn format && git add -A .

# .husky/pre-commit
# Only format TypeScript files
yarn biome format $(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.(ts|tsx)$' | sed 's| |\\ |g') --write
git update-index --again
