name: "Chromatic"

on: push

# on:
#   pull_request_target:
#     types:
#       - closed

jobs:
  # if: github.event_name == 'pull_request' && github.event.action == 'closed'
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run:
          npm install
          # |
          # if [ -e yarn.lock ]; then
          # yarn install --frozen-lockfile
          # elif [ -e package-lock.json ]; then
          # npm ci
          # else
          # npm i
          # fi
      - name: Install ci
        # ⚠️ See your package manager's documentation for the correct command to install dependencies in a CI environment.
        run: npm ci
      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          # ⚠️ Make sure to configure a `CHROMATIC_PROJECT_TOKEN` repository secret
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: packages/ui
          # ⚠️ Make sure to configure a `CHROMATIC_APP_ID` repository secret
