# Workflow name
name: "Jest Deployment"

# Event for the workflow
on: push

# List of jobs
jobs:
  chromatic:
    name: "Run Jest"
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v4
      - run: yarn
      - run: cd packages/server && yarn test:ci
